### ISSUE TITLE
ZHS completion

### ISSUE THREAD

**Issue by martin-hoger** [banyek/MySQL-High-Availability-test#1]
Thank you for the demo at https://asciinema.org/a/14824.

I just wanted to ask you, what kind of zsh completion you use? I like the effect that the text is shown ahead on the line as you type. I have never seen it before.

**Comment by banyek** [comment]
:) It is not zsh, I use fish shell as local shell. http://fishshell.com/

**Comment by martin-hoger** [comment]
I will check it out. Thank you.
